### ISSUE TITLE
Login Problem 

### ISSUE THREAD

**Issue by karanfulare** [karanfulare/Cointab-Login-Challenge#1]
I did this assignment for a interview in a company , it was all working well upto yesterday and today when I presented the file to them in Interview it failed , i even tested the file several times before submitting , Don't know why Javascript or my Fate behaves so , please help me with the user login , the problem statement is " that user should not be able to login for 24 hours for after 5  failed attempts " ,
I achieved this by adding a date variable(named as "time" ) in user schema and a variable named as "login"  , where the login variable increase after each failed attempt and when user.login  == 4 , the date variable( named as"time" in user schema) is increased by 24 hours , AND the only condition when the user can login is when ( user.login < 5 &&  user.time < currentdate ), still the user is able to login after 5 failed attempts . 
files to look -- login.js and User.js

**Comment by bot5294** [comment]
just generated a pull request please check.
